In [1]:
#ML - Classification - Naive bayes - Algorithm

In [2]:
#Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#Reading the dataset
dataset=pd.read_csv("Social_Network_Ads.csv") #Dataset file name
dataset #Function call

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [4]:
dataset=pd.get_dummies(dataset,drop_first=True) #Categorical data converted into numerical data. This technique is called One-Hot Encoding.

In [5]:
dataset

,User ID,Age,EstimatedSalary,Purchased,Gender_Male
0,15624510,19,19000,0,True
1,15810944,35,20000,0,True
2,15668575,26,43000,0,False
3,15603246,27,57000,0,False
4,15804002,19,76000,0,True
...,...,...,...,...,...
395,15691863,46,41000,1,False
396,15706071,51,23000,1,True
397,15654296,50,20000,1,False
398,15755018,36,33000,0,True


In [6]:
dataset=dataset.drop("User ID",axis=1) #Drop - Remove the user ID
dataset

,Age,EstimatedSalary,Purchased,Gender_Male
0,19,19000,0,True
1,35,20000,0,True
2,26,43000,0,False
3,27,57000,0,False
4,19,76000,0,True
...,...,...,...,...
395,46,41000,1,False
396,51,23000,1,True
397,50,20000,1,False
398,36,33000,0,True


In [7]:
dataset["Purchased"].value_counts() #To Identify Balanced or Imbalanced Value Counts

Purchased
0    257
1    143
Name: count, dtype: int64

In [8]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]] #Independent - Input dataset
dep=dataset["Purchased"] #Dependent - Output dataset

In [9]:
indep.shape

(400, 3)

In [10]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [11]:
#split into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [12]:
#Model creation
from sklearn.naive_bayes import GaussianNB  #These first two lines are called as a procedure
classifier =GaussianNB() 
classifier.fit(X_train, y_train) #Fit - Called Function. X-input, Y-output

,priors,None
,var_smoothing,1e-09


In [13]:
y_pred = classifier.predict(X_test) #Evaluation Metric - For Model Evaluation

In [14]:
from sklearn.metrics import confusion_matrix #Confusion Matrix Identification
cm = confusion_matrix(y_test, y_pred)
        

In [15]:
from sklearn.metrics import classification_report #Classification Report
clf_report = classification_report(y_test, y_pred)

In [16]:
print(clf_report) #Function Call

              precision    recall  f1-score   support

           0       0.91      0.94      0.92        85
           1       0.89      0.84      0.86        49

    accuracy                           0.90       134
   macro avg       0.90      0.89      0.89       134
weighted avg       0.90      0.90      0.90       134



In [17]:
print(cm)

[[80  5]
 [ 8 41]]


In [20]:
#Multinomial Naive Bayes
#Model creation
from sklearn.naive_bayes import MultinomialNB  #These first two lines are called as a procedure
classifier = MultinomialNB () 
classifier.fit(X_train, y_train) #Fit - Called Function. X-input, Y-output 

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [21]:
y_pred = classifier.predict(X_test) #Evaluation Metric - For Model Evaluation

In [22]:
from sklearn.metrics import confusion_matrix #Confusion Matrix Identification
cm = confusion_matrix(y_test, y_pred)
        

In [23]:
from sklearn.metrics import classification_report #Classification Report
clf_report = classification_report(y_test, y_pred)

C:\Users\bkann\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\bkann\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\bkann\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [24]:
print(clf_report) #Function Call

              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



In [25]:
print(cm)

[[85  0]
 [49  0]]


In [26]:
#BernoulliNB
#Model creation
from sklearn.naive_bayes import BernoulliNB  #These first two lines are called as a procedure
classifier = BernoulliNB () 
classifier.fit(X_train, y_train) #Fit - Called Function. X-input, Y-output 

,alpha,1.0
,force_alpha,True
,binarize,0.0
,fit_prior,True
,class_prior,None


In [27]:
y_pred = classifier.predict(X_test) #Evaluation Metric - For Model Evaluation

In [28]:
from sklearn.metrics import confusion_matrix #Confusion Matrix Identification
cm = confusion_matrix(y_test, y_pred)
        

In [29]:
from sklearn.metrics import classification_report #Classification Report
clf_report = classification_report(y_test, y_pred)

C:\Users\bkann\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\bkann\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\bkann\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [30]:
print(clf_report) #Function Call

              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



In [31]:
print(cm)

[[85  0]
 [49  0]]


In [32]:
#CategoricalNB
#Model creation
from sklearn.naive_bayes import CategoricalNB  #These first two lines are called as a procedure
classifier = CategoricalNB () 
classifier.fit(X_train, y_train) #Fit - Called Function. X-input, Y-output 

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None
,min_categories,None


In [33]:
y_pred = classifier.predict(X_test) #Evaluation Metric - For Model Evaluation

In [34]:
from sklearn.metrics import confusion_matrix #Confusion Matrix Identification
cm = confusion_matrix(y_test, y_pred)
        

In [35]:
from sklearn.metrics import classification_report #Classification Report
clf_report = classification_report(y_test, y_pred)

In [36]:
print(clf_report) #Function Call

              precision    recall  f1-score   support

           0       0.82      0.96      0.89        85
           1       0.91      0.63      0.75        49

    accuracy                           0.84       134
   macro avg       0.87      0.80      0.82       134
weighted avg       0.85      0.84      0.84       134



In [37]:
print(cm)

[[82  3]
 [18 31]]


In [38]:
#ComplementNB
#Model creation
from sklearn.naive_bayes import ComplementNB  #These first two lines are called as a procedure
classifier = ComplementNB () 
classifier.fit(X_train, y_train) #Fit - Called Function. X-input, Y-output 

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None
,norm,False


In [39]:
y_pred = classifier.predict(X_test) #Evaluation Metric - For Model Evaluation

In [40]:
from sklearn.metrics import confusion_matrix #Confusion Matrix Identification
cm = confusion_matrix(y_test, y_pred)
        

In [41]:
from sklearn.metrics import classification_report #Classification Report
clf_report = classification_report(y_test, y_pred)

In [42]:
print(clf_report) #Function Call

              precision    recall  f1-score   support

           0       0.67      0.47      0.55        85
           1       0.39      0.59      0.47        49

    accuracy                           0.51       134
   macro avg       0.53      0.53      0.51       134
weighted avg       0.57      0.51      0.52       134



In [43]:
print(cm)

[[40 45]
 [20 29]]
